### ISSUE TITLE
Error: Could not locate the bindings file

### ISSUE THREAD

**Issue by jakeslack27** [ezhmd/japanese-db-maker#1]
Hi,

I have followed the instructions to output the sqlite dictionary however I get this error thrown:

![image](https://user-images.githubusercontent.com/20554653/74337873-7d66e900-4de4-11ea-95b1-e957f140b265.png)

Am I missing a prerequisite?

Thanks! Jake

**Comment by ezhmd** [comment]
Hello,

It seems there's something wrong with node-gyp. Can you try installing the module locally instead of globally?

First, make sure that the global japanese-db-maker is uninstalled.
```
npm uninstall -g japanese-db-maker
```

And then
```
# inside the myJpProject folder
npm install japanese-db-maker
npx japanese-db-maker sqlite -s ./sourceFolder -d ./destinationFolder
```

**Comment by jakeslack27** [comment]
Awesome, that solved it and I have the database up and running.  Really appreciate the work and making this available, it was just what I was hoping for, thanks!

**Comment by ezhmd** [comment]
Great! Glad you found this project useful! 
Please consider forking and contributing if you see rooms for improvement. :)
